
- resource: bigquery_datasets
  module_name: load_bigquery_datasets_pipeline
  depends_on: projects
  should_run: true

- resource: firewall_rules
  module_name: load_firewall_rules_pipeline
  depends_on: projects
  should_run: false

- resource: folders
  module_name: load_folders_pipeline
  depends_on: organizations
  should_run: false

- resource: forwarding_rules
  module_name: load_forwarding_rules_pipeline
  depends_on: projects
  should_run: true

- resource: group_members
  module_name: load_group_members_pipeline
  depends_on: groups
  should_run: true

- resource: groups
  module_name: load_groups_pipeline
  depends_on: organizations
  should_run: false

- resource: org_iam_policies
  module_name: load_org_iam_policies_pipeline
  depends_on: organizations
  should_run: true

- resource: organizations
  module_name: load_orgs_pipeline
  depends_on: null
  should_run: true

- resource: buckets_acls
  module_name: load_projects_buckets_acls_pipeline
  depends_on: buckets
  should_run: true

- resource: buckets
  module_name: load_projects_buckets_pipeline
  depends_on: projects
  should_run: false

- resource: cloudsql
  module_name: load_projects_cloudsql_pipeline
  depends_on: projects
  should_run: true

- resource: projects_iam_policies
  module_name: load_projects_iam_policies_pipeline
  depends_on: projects
  should_run: true

- resource: projects
  module_name: load_projects_pipeline
  depends_on: organizations
  should_run: false
  